### ISSUE TITLE
[BUG] the file "user.is-receiving.txt" is blank.

### ISSUE THREAD

**Issue by HumanMus1c** [felipecrs/clipboard-sync#39]
Should I just paste into this file?

![image](https://github.com/felipecrs/clipboard-sync/assets/46023154/dafc88e9-cb16-402c-bac7-d5445b7629ad)
![image](https://github.com/felipecrs/clipboard-sync/assets/46023154/536535bd-4165-4cba-80df-213a59c73522)

**Comment by HumanMus1c** [comment]
I did turn on the "always keep my file on device".

**Comment by felipecrs** [comment]
Such file is just used by other computers to decide whether some other computer is receiving clipboards or not. If none is receiving clipboards, it does not need to keep sending it.

It's blank by design. And I plan to refactor/change this file into a JSON in the future so that it can contain more information.

**Comment by HumanMus1c** [comment]
I would prefer the .txt file format or use multiple formats to process, because I could use the project [ntodotxt](https://github.com/tmaegel/ntodotxt) to sync clipboard file on my mobile phone and easily edit it.

**Comment by felipecrs** [comment]
You are probably mixing two different matters. Remember this file is just a marker to indicate whether there's another computer currently receiving clipboards or not.

You probably meant you'd prefer `.txt` for the clipboard files itself.

And yeah. Earlier versions of this application used to send text clipboards as `.txt` and I also found it nice.

However, in the beginning there was only text/plain clipboard support. Now there is text/rich for formatted text and even bookmark kind for copying links from Edge browser. That's why `.txt` was no longer enough.
